### ISSUE TITLE
storageclass for baremetal/virtualmachine

### ISSUE THREAD

**Issue by livespotty** [Yolean/kubernetes-kafka#165]
Can you let me know which storage class configuration file needs to be executed. I tried docker-storageclass-broker/zookeeper. I get the following error 
kubelet: E0329 22:01:33.070700   11765 desired_state_of_world_populator.go:273] Error processing volume "data" for pod "pzoo-0_kafka(86644deb-33bd-11e8-83f8-005056908071)": error processing PVC "kafka"/"data-pzoo-0": PVC kafka/data-pzoo-0 has non-bound phase ("Pending") or empty pvc.Spec.VolumeName ("")

am I missing something? I am running Nodes on RHEL7.2

**Comment by solsson** [comment]
Since 1.10 the support for [local](https://kubernetes.io/docs/concepts/storage/volumes/#local) volumes is beta. It works really well, if you have pernanent node names. I think there are provisioners, but you can also create the PVC+PV before you create the statefulsets. See example manifests, with storage classes, in https://github.com/Yolean/youkube/tree/master/local-volume/kafka
