### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by FlorinAlexandru** [Yolean/kubernetes-kafka#314]
Hello

Is it possible to create more documentation or more working examples? Or at least to have some StackOverflow tag where we can ask some question.  I'm struggling for 5 days to set-up  a kafka cluster either in cloud (AWS) or on premise. I was expecting that some stuff would have worked out of the box without changes, but in my case I couldn't make anything work.
The only that worked for me was the quickstart but it's not sufficient for my scenario.

Thank you

**Comment by solsson** [comment]
It's a very interesting question. This repository indeed started out with an ambition to document how to set up a Kafka cluster. The effect was that the ratio of questions to contributions went high. I think that it's a fair guess that maintaining such documentation would be a lot more work than maintaining this repository, because the author(s?) wouldn't know your frame of reference, your environment, your ambition etc.

Thus this repo is only about us sharing our Kafka setup. There's no budget for that. At any time we might have broken master, or some condition that made a tagged release run may no longer be true. Thus we're expecting bug reports but there's simply no way to take responsibility for when the repo doesn't deliver what you had expected. Sorry.
