### ISSUE TITLE
Pod always shows in init state

### ISSUE THREAD

**Issue by shashankmjain** [Yolean/kubernetes-kafka#6]
Hi,
I am trying the zookeeper petset deployment . I tried with hostPaths volumes but the pod always shows in init status.
Uploading the modified yaml file

[zookeeper.txt](https://github.com/Yolean/kubernetes-kafka/files/479190/zookeeper.txt)

**Comment by solsson** [comment]
That yaml comes directly from https://github.com/kubernetes/contrib/tree/master/pets. If I remember correctly, I too had issues with init hanging when I tried those examples a while back. It's a bit obscure how an init container installs the application into a generic docker image. I wouldn't recommend this, but because Zookeeper worked in my local tests and in a production cluster I stuck with it.

I'd like to use real zookeeper images. With docker-compose we've used a typicall install, https://hub.docker.com/r/solsson/zookeeper/, but not in a cluster. Now I see there's an [official](https://hub.docker.com/_/zookeeper/) image. If you have the chance to try to modify the yaml to use that one it'd be great.

**Comment by shashankmjain** [comment]
I replace the init container zookeeper image with the docker hub based zookeeper, I still see the same issue

**Comment by solsson** [comment]
Can you fork so I can see what you did? Did you remove the init containers then? Or at least the one that installs zookeeper?

**Comment by juanli2** [comment]
Hi,
I tried to use a NodePort type to expose the kafka service out.
Here's my service yml file:

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 32093
    targetPort: 9092
  selector:
    app: kafka

# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: broker
  namespace: kafka
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka

And here's the service descrition:
# kubectl describe svc kafka -n kafka
Name:                   kafka
Namespace:              kafka
Labels:                 <none>
Selector:               app=kafka
Type:                   NodePort
IP:                     100.73.225.207
Port:                   <unset> 9092/TCP
NodePort:               <unset> 32093/TCP
Endpoints:              10.44.0.10:9092,10.44.0.11:9092,10.44.0.12:9092
Session Affinity:       None

But when I tried using port 32039 external to connect to the kafka service it seems not working.

$  ./bin/kafka-console-producer.sh --broker-list <master-ip>:32093 --topic test2
abc
[2016-11-18 15:26:58,157] ERROR Error when sending message to topic test2 with key: null, value: 3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test2-0 due to 1512 ms has passed since batch creation plus linger time

I'm pretty sure that the connection to the master-ip is working, and the port 32039 is listening in the cluster.

It works for the zookeeper, but I'm not sure why the kafka not working

**Comment by solsson** [comment]
Closing this because https://github.com/Yolean/kubernetes-kafka/releases/tag/v2.0.0 changes init quite a bit.
