### ISSUE TITLE
Dockerfiles

### ISSUE THREAD

**Issue by bfabec** [Yolean/kubernetes-kafka#87]
Hi @solsson - thanks for the nicely organized project!  Do you have the Dockerfiles located somewhere for the broker and zookeeper that are being referenced for the images?  I didn't see any links for them.

Thanks!

**Comment by bfabec** [comment]
Also, can you give me your thoughts on the benefits of having two types of zookeepers (persistent and ephemeral)?

**Comment by solsson** [comment]
Docker builds are automated on [Docker hub](https://hub.docker.com/) which makes them easy to fork and build for yourself -- no client side tooling needed. As with all automated builds, see the link under "Source Repository", for example at [solsson/kafka](https://hub.docker.com/r/solsson/kafka/).

The origin of the two zookeeper statefulsets is #34. We have a three-zone cluster in GKE, and without the replicas that travel freely between zones I thought a 5-node zk cluster would (if the "wrong" zone goes out) be too close for comfort to not be able to form a quorum.

Closing because there is no actual issue here. I'm fine with questions as issues though, as there's no other tool for it.
